# Generated by Django 4.1.7 on 2023-03-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Trajanje kviza u minutima')),
                ('required_score_to_pass', models.IntegerField(help_text='potrebni bodovi u %')),
                ('difficulty', models.CharField(choices=[('lako', 'lako'), ('srednje', 'srednje'), ('tesko', 'tesko')], max_length=7)),
            ],
        ),
    ]
